name: MatrixChain pre-commit and post-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install uv
        uses: astral-sh/setup-uv@v5

      - name: set common environment
        run: |
          uv venv
          source .venv/bin/activate
          uv sync
          {
            echo "VIRTUAL_ENV=$VIRTUAL_ENV"
          } >> "$GITHUB_ENV"
      
      - name: install conan
        run: |
          pip install conan
          conan profile detect --force
          conan remote add conan_packages ${{ secrets.CONAN_ADDRESS }}
  
      - name: CMake release config
        run: |
          conan install . --build=missing -s compiler.cppstd=gnu20 -s build_type=Release
          cmake --preset release
          cmake --build build

      - name: CMake release test
        run: ctest --test-dir build --rerun-failed --output-on-failure

      - name: clear build after release test
        run: rm -rf build

      - name: CMake debug config
        run: |
          conan install . --build=missing -s compiler.cppstd=gnu20 -s build_type=Debug
          cmake --preset debug
          cmake --build build

      - name: CMake debug test
        run: ctest --test-dir build --rerun-failed --output-on-failure